## Тема “Вычисления с помощью Numpy”

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [49]:
import numpy as np

In [50]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(f"Массив a: \n{a}")
print(f"Размерность масива a: {a.ndim}")
print(f"Форма массива a: {a.shape}")
print(f"Количество элементов массива: {a.size}")

Массив a: 
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность масива a: 2
Форма массива a: (5, 2)
Количество элементов массива: 10


In [51]:
mean_a = np.array(a.mean(axis=0))

In [52]:
print(f"Массив со средними значениями признаков: {mean_a}")

Массив со средними значениями признаков: [2.  8.4]


### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [53]:
a_centered = a - mean_a

In [54]:
print(f"Результирующий массив: \n{a_centered}")

Результирующий массив: 
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [55]:
column_1 = a_centered[:, 0]

In [56]:
column_2 = a_centered[:, 1]

In [57]:
a_centered_sp = column_1.dot(column_2)

In [58]:
print(f"Скалярное произведение столбцов массива a_centered: {a_centered_sp}")

Скалярное произведение столбцов массива a_centered: 8.0


In [59]:
result = a_centered_sp / (len(a_centered) - 1)

In [60]:
print(f"Конечный результат: {result}")

Конечный результат: 2.0


### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [61]:
a_t = np.transpose(a)

In [62]:
print(f"Транспонированная матрица a: \n{a_t}")

Транспонированная матрица a: 
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [63]:
result = np.cov(a_t)[0, 1]

In [64]:
print(f"Конечный результат: {result}")

Конечный результат: 2.0


## Тема “Работа с данными в Pandas”

### Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [65]:
import pandas as pd

In [66]:
authors = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}

In [67]:
authors = pd.DataFrame(authors)

In [68]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [69]:
authors.shape

(3, 2)

In [70]:
authors.columns

Index(['author_id', 'author_name'], dtype='object')

In [71]:
authors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   author_id    3 non-null      int64 
 1   author_name  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [72]:
authors.describe()

author_id
count        3.0
mean         2.0
std          1.0
min          1.0
25%          1.5
50%          2.0
75%          2.5
max          3.0

In [73]:
book = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

In [74]:
book = pd.DataFrame(book)

In [75]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [76]:
book.shape

(7, 3)

In [77]:
book.columns

Index(['author_id', 'book_title', 'price'], dtype='object')

In [78]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   author_id   7 non-null      int64 
 1   book_title  7 non-null      object
 2   price       7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes


In [79]:
book.describe()

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [80]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')

In [81]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [82]:
top5 = authors_price.nlargest(5, 'price')

In [83]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [84]:
authors_price['min_price'] = authors_price['price']

In [85]:
authors_price['max_price'] = authors_price['price']

In [86]:
authors_price['mean_price'] = authors_price['price']

Можно ли код трёх вышележащих строк прописать в одну строку?

In [87]:
authors_price

author_id author_name            book_title  price  min_price  max_price  \
0          1    Тургенев           Отцы и дети    450        450        450   
1          1    Тургенев                 Рудин    300        300        300   
2          1    Тургенев     Дворянское гнездо    350        350        350   
3          2       Чехов      Толстый и тонкий    500        500        500   
4          2       Чехов       Дама с собачкой    450        450        450   
5          3  Островский                 Гроза    370        370        370   
6          3  Островский  Таланты и поклонники    290        290        290   

   mean_price  
0         450  
1         300  
2         350  
3         500  
4         450  
5         370  
6         290

In [88]:
authors_stat = authors_price.groupby('author_name').agg({'min_price': 'min', 'max_price': 'max', 'mean_price': 'mean'})

In [89]:
authors_price.drop('min_price', axis=1, inplace=True)

In [90]:
authors_price.drop('max_price', axis=1, inplace=True)

In [91]:
authors_price.drop('mean_price', axis=1, inplace=True)

In [92]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [93]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [98]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [99]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [101]:
? pd.pivot_table

In [112]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name',
                          columns=['cover'], aggfunc=np.sum, fill_value=0)

In [114]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [115]:
book_info.to_pickle('book_info.pkl')

In [117]:
book_info2 = pd.read_pickle('book_info.pkl')

In [118]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950